### ISSUE TITLE
setStatus not working 

### ISSUE THREAD

**Issue by theo-bnts** [fnbrjs/fnbr.js#1]
```jsXMPP-Client disconnecting...
\fnbr\src\Client\index.js:490
      this.config.status = status;
                         ^

TypeError: Cannot assign to read only property 'status' of object '#<Object>'
    at Client.setStatus (C:\Users\Theo\Documents\Bots Discord\Bot CMaker\node_modules\fnbr\src\Client\index.js:490:26)
    at EventEmitter.<anonymous> (C:\Users\Theo\Documents\Bots Discord\Bot CMaker\events\my\cmaker0fnbr.js:136:16)
    at EventEmitter.emit (events.js:314:20)
    at Timeout.eachSecond [as _onTimeout] (C:\Users\Theo\Documents\Bots Discord\Bot CMaker\node_modules\date-events\index.js:112:17)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)```

It's just so you can remember. 👍

**Comment by AlexT2** [comment]
fixed in a543b1a63650f1ea0d059e71e683594e9778ab90 and released 1.0.1 on npm
